server:
  port: 8080

spring:
  application:
    name: chat-deepseek
  ai:
    deepseek:
      api-key: ${AI_DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
      embedding:
        enabled: false
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          # 默认模型也是qwen-plus
          model: qwen-plus