server:
  port: 8092
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: mcp-client-webflux
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
    mcp:
      client:
        sse:
          connections:
            richWoman:
              # 实际的连接地址为：http://localhost:8091/sse/mcp
              url: http://localhost:8091/
        toolcallback:
          enabled: true

  mandatory-file-encoding: UTF-8


# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG