server:
  port: 8094

spring:
  application:
    name: nacos-mcp-client
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          # 默认模型也是qwen-plus
          model: qwen-plus
    mcp:
      client:
        enabled: true
        name: my-nacos-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC  # or ASYNC for reactive applications

    alibaba:
      mcp:
        nacos:
          namespace: 2130ad98-0e60-41ce-a4de-2146b252b9dc
          server-addr: 127.0.0.1:28848
          username: nacos
          password: Nacos@168
          client:
            enabled: true
            sse:
              connections:
                server1:
                  service-name: rich-woman-server
                  version: 0.0.2


# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG
