server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG


# NOTE: You must disable the banner and the console logging
# to allow the STDIO transport to work !!!
# Config reference: https://docs.spring.io/spring-ai/reference/api/mcp/mcp-server-boot-starter-docs.html#_webflux_server_configuration
spring:
  main:
    banner-mode: off
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
    mcp:
      client:
        stdio:
          servers-configuration: classpath:/mcp-servers-config.json
          # 直接配置
          # connections:
          #   server1:
          #     command: java
          #     args:
          #       - -jar
          #       - E:\GithubRepo\spring-ai-alibaba-demo\spring-ai-alibaba-mcp\quick-start\mcp-server\target\mcp-server.jar  # 放一个绝对路径，修改为server jar包所在位置
  mandatory-file-encoding: UTF-8

