server:
  port: 8081

spring:
  application:
    name: chat-dashscope
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          # 默认模型也是qwen-plus
          model: qwen-plus
    memory:
      redis:
        port: 6379
        host: 127.0.0.1
      mysql:
        enabled: true

    chat:
      memory:
        repository:
          jdbc:
            mysql:
              enabled: true
              driver-class-name: com.mysql.cj.jdbc.Driver
              jdbc-url: jdbc:mysql://localhost:3306/spring_ai_alibaba_mysql?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrl
              username: root
              password: root
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
