server:
  port: 8091

# NOTE: You must disable the banner and the console logging
# to allow the STDIO transport to work !!!
# Config reference: https://docs.spring.io/spring-ai/reference/api/mcp/mcp-server-boot-starter-docs.html#_webflux_server_configuration
spring:
  application:
    name: mcp-server-webflux
  ai:
    mcp:
      server:
        name: rich-woman-server
        version: 0.0.1
        type: ASYNC  # Recommended for reactive applications
        # 配置 sse 的根路径，默认值为 /sse
        # 下面的最终路径为 ip:port/sse/mcp
        sse-endpoint: /sse
        sse-message-endpoint: /mcp
        instructions: 这个是中国富婆信息查询和资源
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true


