server:
  port: 8097

spring:
  application:
    name: mcp-server-annotations

  ai:
    mcp:
      server:
        name: fortune-server
        version: 1.0.0
        type: SYNC
        protocol: SSE  # or STDIO, STREAMABLE
        capabilities:
          tools: true
          logging: true