server:
  port: 8087

spring:
  application:
    name: spring-ai-alibaba-rag-evaluation

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      embedding:
        options:
          model: text-embedding-v1