server:
  port: 8093

spring:
  application:
    name: mcp-server-nacos
  ai:
    mcp:
      server:
        name: rich-woman-server
        version: 0.0.2
        type: SYNC  # Recommended for reactive applications
        instructions: "富婆通讯录MCP服务"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true

    alibaba:
      mcp:
        nacos:
          namespace: 2130ad98-0e60-41ce-a4de-2146b252b9dc
          server-addr: 127.0.0.1:28848
          username: nacos
          password: Nacos@168
          register:
            enabled: true
            service-group: mcp-server
            service-name: rich-woman-server



